default: &default
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  adapter: postgresql
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: deployqa_development

test:
  <<: *default
  database: deployqa_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
